# Generated by Django 6.0.2 on 2026-02-28 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('documents', 'Documents'), ('clothing', 'Clothing'), ('accessories', 'Accessories'), ('keys', 'Keys'), ('bags', 'Bags & Wallets'), ('others', 'Others')], default='others', max_length=20)),
                ('item_type', models.CharField(choices=[('lost', 'Lost'), ('found', 'Found')], max_length=10)),
                ('location', models.CharField(max_length=200)),
                ('date_reported', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('claimed', 'Claimed'), ('closed', 'Closed')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClaimRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Describe why you believe this item belongs to you')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claimant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='items.item')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
